# Generated by Django 4.1.3 on 2022-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
